#HELLOWORLD 10.22PM
#DATE - MONDAY.20-JULY-2026

#THIS PROGRAMME IS ABOUT THE EXPONENTS IN MATHEMATICS  AND IN PYTHON.
#EXPONENETS CAN BE DEFINED AS EXPONENT MULTIPLY A NUMBER O ITSELF A SPECIFIED NUMBER OF TIMES. 

#I HAVE ADDED MORE ABOUT EXPONENTS IN MY NOTES AND I WILL UPLOAD THE NOTES AFTER THE COMPLETION OF MY 01-BASIC MATHS IN BASIC MATHS I WILL UPLOAD IT AS NAMED AS BASIC_MATHS. 


#HERE IS THE EXAMPLE OF EXPONENT EXAMPLE. 


from sympy import * 
x = symbols('x') 
expr = x**2 / x**5 
print(expr)